name: chat_location
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  chat_repository:
    path: packages/chat_repository
  chat_ui:
    path: packages/chat_ui
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.1.0
  mocktail: ^0.1.0
  mocktail_image_network: ^0.1.0
  very_good_analysis: ^2.3.0

dependency_overrides:
  stream_chat:
    git:
      url: https://github.com/GetStream/stream-chat-flutter
      path: packages/stream_chat
      ref: 6f677de5287646a802b8b809a3ee0592d355d4b5
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter
      path: packages/stream_chat_flutter
      ref: 6f677de5287646a802b8b809a3ee0592d355d4b5
  stream_chat_flutter_core:
    git:
      url: https://github.com/GetStream/stream-chat-flutter
      path: packages/stream_chat_flutter_core
      ref: 6f677de5287646a802b8b809a3ee0592d355d4b5

flutter:
  uses-material-design: true
  generate: true
