name: chat_ui
description: Flutter package which exposes reusable chat UI components
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_chat_flutter: ^2.0.0-nullsafety.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.0