name: chat_repository
description: Dart package which manages the chat domain
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  stream_chat: ^2.0.0-nullsafety.7

dev_dependencies:
  mocktail: ^0.1.4
  test: ^1.17.0
  very_good_analysis: ^2.1.0
