name: chat_repository
description: Package which manages the chat domain
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^4.3.0
  stream_chat: ^2.0.0-nullsafety.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4  
  very_good_analysis: ^2.1.0
