name: chat_repository
description: Package which manages the chat domain
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^4.3.0
  stream_chat_flutter: 
    git:
      url: https://github.com/GetStream/stream-chat-flutter
      path: packages/stream_chat_flutter
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0
